### ISSUE TITLE
If underlying collection triggers any event we don't handle, re-trigger it.

### ISSUE THREAD

**Issue by dlikhten** [dlikhten/filtered-collection#12]
Propagate all events from the original collection.

**Comment by jkeen** [comment]
Not sure if this is related but an older version of this (from a year ago, not sure of the version number) used to bubble up property change events, but the newest version does not. I'm trying to track it down.

This used to work:  `this.listenTo(this.collection, 'change:blah', this.blahHandler)`

New version does not fire that event, but rather only a general 'change' event. Here's a jasmine test that tests for the behavior:

```
  it("property change events are fired on filtered collection", function() {
    var collection         = new Backbone.Collection([ {id: 1, difficulty: 1}, {id: 2, difficulty: 2}, {id: 3, difficulty: 1}, {id: 4, difficulty: 3} ]);
    var filteredCollection = new Backbone.FilteredCollection(null, {collection: collection});
    filteredCollection.setFilter(function(d) { return (d.get('difficulty') === 1) });

    var changeCount = 0;
    var newModel = new Backbone.Model({id: 5, difficulty: 1});
    collection.add(newModel);

    filteredCollection.on("change:blah", function() { changeCount  = changeCount + 1; });

    newModel.set({"blah": "blah"});

    expect(changeCount).toEqual(1);
  });
```

**Comment by dlikhten** [comment]
Interesting. This could be because I override backbone's change listener so it would not propagate that change event. Something to look into. Thanks for the test.

**Comment by maiwald** [comment]
:+1: We'd love to see those events propagated as well :)

**Comment by Calamari** [comment]
Thanks @jkeen for the test

**Comment by dlikhten** [comment]
Ok I seriously need to do some merging today :). I'm trying to remember why I disabled the change event propagation. It doesn't make sense that I would...

First of all I think this commit from paginated-collection should be similar to what I want to do here: https://github.com/dlikhten/paginated-collection/commit/c85f9aced3d14f077b98d0e61d43b69df053f411

And then I'll integrate the unit tests and see what is going on. Thanks for the commits @Calamari.

**Comment by Calamari** [comment]
Just want to ask, what the status is about that pull request and that problem? :-)

**Comment by dlikhten** [comment]
Oy im sorry, i've been too forgetful. It's on my calendar. You can hold me accountable for merging it in tonight.

**Comment by jkeen** [comment]
Cooooooool, thanks for getting this in.
