### ISSUE TITLE
Adding version number

### ISSUE THREAD

**Issue by seanmhoffman** [dlikhten/filtered-collection#8]
Is it possible that you could include a version number on your next update. I ran into some problems with the older version of the plugin and didn't realize that I wasn't working on the most current version until reading through the code to see the differences.

**Comment by dlikhten** [comment]
Added the first official version :) Sorry, forgot to close this ticket.

https://github.com/dlikhten/filtered-collection/commit/c964b14aaca3b5b72b8d5759b1ca34f032f002de

Hopefully to make up for the delay, here's something awesome.

![cat-riding-a-fire-breathing-unicorn-16414-1920x1080](https://f.cloud.github.com/assets/14067/733267/0cdd51fe-e29a-11e2-939f-d5197623a509.jpg)

**Comment by seanmhoffman** [comment]
Thanks, definitely made up for the delay.

**Comment by dlikhten** [comment]
Alright, good to know. ^_^
